### ISSUE TITLE
MyNextManager Nest login error page

### ISSUE THREAD

**Issue by petegreek** [yracine/device-type-myNext#1]
Hi i just purchased your nest thermostat code (very quick download - thanks) however I keep hitting the below error when trying to enter my Nest login details. Could you please advised what I need to do? thanks 
![IMG_9511](https://user-images.githubusercontent.com/34242129/56805798-03984b80-6822-11e9-8b7d-8b787b328a87.JPG)
![IMG_9510](https://user-images.githubusercontent.com/34242129/56805842-2165b080-6822-11e9-8adc-d81aa12208e8.JPG)

**Comment by yracine** [comment]
Hi, there are some Nest server issues... You need to wait till they solve their internal issues.

I have the same login issue if you try to access the Nest Console at:

https://home.nest.com/login

In the future, please send any issues to my gmail account: services@maisonsecomatiq.com.

The github is only for the README install instructions and the complimentary smartapps.

Regards.
