### ISSUE TITLE
No information

### ISSUE THREAD

**Issue by dastar5626** [yracine/device-type-myNext#2]
Hello

My tstat is showing but no information is being populated.

Thank you

**Comment by yracine** [comment]
Hi, please refer to the Readme on the proper prerequisites and installation
steps:


https://github.com/yracine/device-type-myNext

If the tstat is showing with no values, it's more likely that your login
information is incorrect (cookie, url), please refer to the following link
(with screenshots) to get the right login info.

https://thingsthataresmart.wiki/index.php?title=My_NextServiceMgr#14b.29_LOGIN_INFO_REQUIRED_FOR_GOOGLE_ACCOUNT_USERS_.28MIGRATED_NEST_USERS.29

Do not open issues in github as I usually don't check here, send your questions to services@maisonsecomatiq.com. 

P. S. I cannot help without logs. In the community wiki above, you can find
some instructions on how to extract the logs from your account.
